### ISSUE TITLE
[AUR] first pearl init is called in install process

### ISSUE THREAD

**Issue by Snogard** [pearl-core/pearl#109]
### What is the problem
During the install process of the package, pearl init, is called. This causes to run pearl as root thus modifying the root user files.

### Suggested fix
If the intention was to autoconfigure pearl after installation, the method currently in use won't work for normal users and it can have unwanted changes to the root user.
I suggest to remove the auto configuration at install time and just print out a message reminding the user what needs to be done to complete the configuration.

**Comment by fsquillace** [comment]
The approach makes sense to me.

**Comment by Snogard** [comment]
Are you referring to the current approach or the suggested one?

**Comment by fsquillace** [comment]
I meant the suggested one. I updated the aur package. Closing.
