### ISSUE TITLE
Add the option to initialize pearl only to a specific shell or program

### ISSUE THREAD

**Issue by Snogard** [pearl-core/pearl#111]
### What is the Problem?
Since i don't use vim, emacs, bash or fish i don't have their .*rc files in my home directory, but if i run pearl init, pearl will create those files with only even if i do not use them.
I would like to be able to specify to pearl what program i want to be initialized.

### Suggested fix
Here is how i would imagine the implementation:
- pearl init: initializes pearl without writing to .*rc files and reminds the user to do so himself
- pearl init <programs list>: initializes pearl and writes to .*rc files of specified programs
- pearl init [-a/--all]: initializes pearl and writes to all .*rc files supported by pearl
- pearl init [-p/--print] <programs list>: initializes pearl and tells the user what to change in the .*rc files of the specified programs

You don't have to use those exact options or paradigm, those are just examples to better convey what i would like to be able to do with pearl.

**Comment by fsquillace** [comment]
This is something I also thought long time ago. While giving the option to the user is definitely a good way I think it kind of degrade the user experience. For instance, if someone is installing a vim related package the user will also need to remember to init pearl for vim config file and that's definitely not ideal.

The current solution is not ideal either but it was the simplest way to solve the problem. There are other programs out there that work in the same way.
A better option is to have a lazy initialization https://github.com/pearl-core/pearl/issues/112

Closing this in favor of lazy init approach.
