### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Tsutsukakushi** [pearl-core/pearl#45]
> Pearl  
> Because only in the best Shells you will find a Pearl...

> curl -sL https://git.io/vV4yE | sh

REMOVED THE OFFENSIVE QUESTION

**Comment by fsquillace** [comment]
Hi,

From you message is quite unclear what problem you want to raise.

Certainly, you question is rude and against any code of conduct.

**Comment by Tsutsukakushi** [comment]
> From your message is quite unclear what problem you want to raise.

Read the last line I quoted.

**Comment by fsquillace** [comment]
I knew which problem you wanted to raise but,
again, you had just to explain that using pipe is a bad pattern that might raise problem on running malicious code and not your uneducated question.

**Comment by Tsutsukakushi** [comment]
> you had just to explain that using pipe is a bad pattern that might raise problem on running malicious code and not your uneducated question

The question was a test to see if I should follow the project or just forget it. You failed it so I will forget it after this comment.
