### ISSUE TITLE
pearl now supported in topgrade

### ISSUE THREAD

**Issue by go2null** [pearl-core/pearl#89]
Just an FYI: https://github.com/r-darwish/topgrade/issues/126

**Comment by fsquillace** [comment]
Interesting thanks!

Just for FYI, you can achieve something really similar to `topgrade` by creating a pearl package which updates all things that you need in you system.

A simple example is [Ibis](https://github.com/fsquillace/ibis) which updates the Arch Linux with additional packages. Moreover, it also configures them and runs the basic services required for a minimal workable Arch Linux.

**Comment by fsquillace** [comment]
Add PR for fixing the doc: https://github.com/r-darwish/topgrade/pull/128

**Comment by go2null** [comment]
FYI - https://github.com/r-darwish/topgrade/pull/128 merged.

> Just for FYI, you can achieve something really similar to topgrade by creating a pearl package which updates all things that you need in you system.

interesting ...
